language: node_js
node_js:
- "6.1"
before_install:
- "npm install -g yarn"
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb startk
cache:
  directories:
  - "$HOME/.yarn-cache"
install:
- "yarn"